"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
linemode = "mtime"
ratio = [1,2,3]
show_hidden = false
sort_by = "natural"
sort_dir_first = true
sort_sensitive = true
sort_translit = false

[preview]
tab_size = 4

